image: erlang:21.2

before_script:
  - apt-get -q update
  - apt-get -qy install cmake libsnappy-dev

test:
  artifacts:
    when: always
    paths:
    - _build/test/logs
    - _build/test/cover

  script:
    - make test cover

  cache:
    paths:
    - _build/default/lib/rocksdb
    - _build/test/lib/rocksdb
