image: erlang:20

test:
  artifacts:
    when: always
    paths:
    - _build/test/logs
    - _build/test/cover

  script:
    - make test cover

  cache:
    paths:
    - _build/default/lib/rocksdb
    - _build/test/lib/rocksdb